//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Scripts/Utils/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Envy
{
    public partial class @Input : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Input()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""InputMap"",
            ""id"": ""debed3d9-350c-4a12-bda0-c6cf399c9fa8"",
            ""actions"": [
                {
                    ""name"": ""Input"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0e847b36-ccf7-499f-bdf3-aff3755825dc"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8caa8583-5a82-4f46-9145-b86e6777e1d7"",
                    ""path"": ""<Touchscreen>/touch0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // InputMap
            m_InputMap = asset.FindActionMap("InputMap", throwIfNotFound: true);
            m_InputMap_Input = m_InputMap.FindAction("Input", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // InputMap
        private readonly InputActionMap m_InputMap;
        private IInputMapActions m_InputMapActionsCallbackInterface;
        private readonly InputAction m_InputMap_Input;
        public struct InputMapActions
        {
            private @Input m_Wrapper;
            public InputMapActions(@Input wrapper) { m_Wrapper = wrapper; }
            public InputAction @Input => m_Wrapper.m_InputMap_Input;
            public InputActionMap Get() { return m_Wrapper.m_InputMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(InputMapActions set) { return set.Get(); }
            public void SetCallbacks(IInputMapActions instance)
            {
                if (m_Wrapper.m_InputMapActionsCallbackInterface != null)
                {
                    @Input.started -= m_Wrapper.m_InputMapActionsCallbackInterface.OnInput;
                    @Input.performed -= m_Wrapper.m_InputMapActionsCallbackInterface.OnInput;
                    @Input.canceled -= m_Wrapper.m_InputMapActionsCallbackInterface.OnInput;
                }
                m_Wrapper.m_InputMapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Input.started += instance.OnInput;
                    @Input.performed += instance.OnInput;
                    @Input.canceled += instance.OnInput;
                }
            }
        }
        public InputMapActions @InputMap => new InputMapActions(this);
        public interface IInputMapActions
        {
            void OnInput(InputAction.CallbackContext context);
        }
    }
}
